[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[dependencies]
forge-std = "https://github.com/foundry-rs/forge-std"

[profile.ci.fuzz]
runs = 10000

[etherscan]
key = { key = "$ETHERSCAN_API_KEY" }

[env]
dotenv = ".env"